### ISSUE TITLE
I2C on Agema-ag7648 missing devices

### ISSUE THREAD

**Issue by opcode02** [bisdn/basebox#229]
## Expected Behavior

ofagent looks for devices: /dev/i2c-3 and /dev/i2c-2 but they are not found on the ag7648 running the 19.06 release.

running ofagent by hand (since it crashes and restarts through systemd):

root@agema-ag7648:~# /usr/sbin/ofagent -a=20
initializing
10-22 15:37:58.095739 [ofagent] version 0.0.0.0 [  267.623270] ofagent[2061]: segfault at 0 ip 00000000004041ed sp 00007ffd70655440 error 4-- Built on Thu  in ofagent[403000+19b000]Jun 27 2019 at 0
9:53:08 UTC
OF [  267.638516] audit: type=1701 audit(1571758678.097:9): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=2061 comm="ofagent" exe="/usr/sbin/ofagent" sig=11
Datapath ID: 0x000000000000DA7A
Initializing the system.
10-22 15:37:58.095739 [socketmanager] Initializing socket manager
10-22 15:37:58.096739 [ofstatemanager] Registered gentable "test" with table id 0
10-22 15:37:58.096739 [socketmanager] Enabling OF socket mgr
10-22 15:37:58.096739 [ofconnectionmanager] Enabling OF connection mgr
10-22 15:37:58.096739 [ofstatemanager] Enabling OF state mgr
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-3 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-2 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-2 (0x2): No such file or directory
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-2 (0x2): No such file or directory
10-22 15:37:58.096739 [x86_64_delta_ag7648] Unable to read the 0 reg

10-22 15:37:58.096739 [onlplib] ONIE data is not in TlvInfo format.
10-22 15:37:58.096739 [onlplib] failed to open file /dev/i2c-2 (0x2): No such file or directory
10-22 15:37:58.096739 [ofagent] got serial number: (null)
Segmentation fault (core dumped)

## Actual Behavior

only 2 i2c devices are found:

root@agema-ag7648:~# ls -la /dev/i2c-*
crw-------    1 root     root       89,   0 Oct 22 15:36 /dev/i2c-0
crw-------    1 root     root       89,   1 Oct 22 15:36 /dev/i2c-1

## Steps to Reproduce the Problem

Install 19.06 BISDN on a ag7648 switch. 

## Specifications
  - Version: 19.06
  - Platform: Delta Agema
  - Subsystem: AG7658

Its also useful to note that if I boot the switch into ODM: DIAG mode, and dump the i2c devices from there I see all the i2c devices.

AG7648-DIAG> show i2c devices
NAME             BUS  ADDR    MUX       STATUS
---------------------------------------------------
       CLOCK_GEN    0 69(d2)            OK
          DDR_VR    0 2e(5c)            OK
    DDR_MODULE_0    0 52(a4)            OK
    DDR_MODULE_1    0 53(a6)            N/A
     System_CPLD    2 31(62)            OK
     Master_CPLD    2 32(64)            OK
      Slave_CPLD    2 33(66)            OK
           TMP75    2 4d(9a)            OK
       ID_EEPROM    2 53(a6)            OK
         TMP75-C    3 4c(98)            OK
         TMP75-D    3 4d(9a)            OK
         TMP75-E    3 4e(9c)            OK
        HotSwap2    3 42(84)            OK
        HotSwap1    3 40(80)            OK
     FAN3-EEPROM    3 53(a6)            OK
     FAN2-EEPROM    3 52(a4)            OK
     FAN1-EEPROM    3 51(a2)            OK
       FAN-CTRL1    3 29(52)            OK
       FAN-CTRL2    3 2a(54)            OK
     AVS-PWR-RSV    3 2c(58)            OK
            SFP1    4 50(a0)  1         N/A
            SFP2    4 50(a0)  2         N/A
            SFP3    4 50(a0)  3         N/A
            SFP4    4 50(a0)  4         N/A
            SFP5    4 50(a0)  5         N/A
            SFP6    4 50(a0)  6         N/A
            SFP7    4 50(a0)  7         N/A
            SFP8    4 50(a0)  8         N/A
            SFP9    4 50(a0)  9         N/A
           SFP10    4 50(a0)  10        N/A
           SFP11    4 50(a0)  11        N/A
           SFP12    4 50(a0)  12        N/A
           SFP13    4 50(a0)  13        N/A
           SFP14    4 50(a0)  14        N/A
           SFP15    4 50(a0)  15        N/A
           SFP16    4 50(a0)  16        N/A
           SFP17    4 50(a0)  17        N/A
           SFP18    4 50(a0)  18        N/A
           SFP19    4 50(a0)  19        N/A
           SFP20    4 50(a0)  20        N/A
           SFP21    4 50(a0)  21        N/A
           SFP22    4 50(a0)  22        N/A
           SFP23    4 50(a0)  23        N/A
           SFP24    4 50(a0)  24        N/A
           SFP25    4 50(a0)  25        N/A
           SFP26    4 50(a0)  26        N/A
           SFP27    4 50(a0)  27        N/A
           SFP28    4 50(a0)  28        N/A
           SFP29    4 50(a0)  29        N/A
           SFP30    4 50(a0)  30        N/A
           SFP31    4 50(a0)  31        N/A
           SFP32    4 50(a0)  32        N/A
           SFP33    4 50(a0)  33        N/A
           SFP34    4 50(a0)  34        N/A
           SFP35    4 50(a0)  35        N/A
           SFP36    4 50(a0)  36        N/A
           SFP37    4 50(a0)  37        N/A
           SFP38    4 50(a0)  38        N/A
           SFP39    4 50(a0)  39        N/A
           SFP40    4 50(a0)  40        N/A
           SFP41    4 50(a0)  41        N/A
           SFP42    4 50(a0)  42        N/A
           SFP43    4 50(a0)  43        N/A
           SFP44    4 50(a0)  44        N/A
           SFP45    4 50(a0)  45        N/A
           SFP46    4 50(a0)  46        N/A
           SFP47    4 50(a0)  47        N/A
           SFP48    4 50(a0)  48        N/A
          QSFP49    5 50(a0)  0         N/A
          QSFP50    5 50(a0)  1         N/A
          QSFP51    5 50(a0)  2         N/A
          QSFP52    5 50(a0)  3         N/A
          QSFP53    5 50(a0)  4         N/A
          QSFP54    5 50(a0)  5         N/A
     PSU2-EEPROM    6 51(a2)            OK
     PSU1-EEPROM    6 50(a0)            OK
         PSU2-PM    6 59(b2)            OK
         PSU1-PM    6 58(b0)            OK

After more digging I see the diag mode loads a different module (here is a snippet of the diag mode's kernel boot). 
i2c /dev entries driver
i801_smbus 0000:00:1f.3: PCI->APIC IRQ transform: INT B -> IRQ 18
i801_smbus 0000:00:1f.3: SMBus using PCI Interrupt
ismt_smbus 0000:00:13.0: PCI->APIC IRQ transform: INT A -> IRQ 16
ismt_smbus 0000:00:13.0: irq 54 for MSI/MSI-X
i2c i2c-1: Added multiplexed i2c bus 2
i2c i2c-1: Added multiplexed i2c bus 3
i2c i2c-1: Added multiplexed i2c bus 4
i2c i2c-1: Added multiplexed i2c bus 5
i2c i2c-1: Added multiplexed i2c bus 6
i2c i2c-1: Added multiplexed i2c bus 7
i2c i2c-1: Added multiplexed i2c bus 8
i2c i2c-1: Added multiplexed i2c bus 9
pca954x 1-0070: registered 8 multiplexed busses for I2C mux pca9547

Note the pca954x driver finding a pac9547, but when we boot into bisdn that driver doesn't seem to be loaded.

**Comment by rubensfig** [comment]
Hello!

Thank you for your feedback. The image you tried was probably untested, and due to a buildchain upgrade it is not possible anymore to try to fix this specific error.

I suggest however trying the image present on the following link: 

http://bisdn-switch-images.s3-eu-central-1.amazonaws.com/release_candidates/agema-ag7648/onie-bisdn-agema-ag7648-20190821.bin

In the switch present in our lab I can currently see the devices, and ofagent appears to be working.

**Comment by opcode02** [comment]
I assume you realize yesterday (10/23) I was working with Tac from Tibit trying to get this working on our ag7648. We tried several images, but all seemed to exhibit the same behavior. I also tried the image you linked above and it still has the same issue.

Is there any other details you need? I can easily get anything of our our ag7648 for you.

**Comment by hwoesner** [comment]
Hi Shane, 
We tried several things over yesterday and today to be able to reproduce this behavior. 
I tried all the images you tried on our (3) Ag7648, and all worked fine. Also Durga from Delta confirmed the images to be working on her switch. Difficult to reproduce, that is.
I spoke to Milo Tseng of Delta if by chance you might be running on a different hardware revision, but the serial number Tac gave us is indeed just the same plain 7648 Trident2 that we have. Milo would be willing to send another switch only to make sure it is not some hardware bug (which is unlikely, given the DIAG works).
All that is left for me right now is to ask you to do a clean uninstall of the network OS from the ONIE boot menu before reinstalling. This takes additional time, as the partitions are erased then, but we have seen issues when the newly installed image is smaller than the previously installed one. 

Then, a full dmesg boot log would be helpful. The fact that ofagent crashes before it is even reading out the SN hints to the CPLD driver not being properly loaded. 
Sorry for the headache this is creating already before actually being able to start, but I am running out of ideas for now. Let me know if you get any further.
Hagen

**Comment by opcode02** [comment]
OK, just to rule out a possible memory problem I'm going to run MemTest86 overnight to make sure we don't have any obvious memory issues. After that will do a format through ONIE and try that linked image again. Thanks for the help.

**Comment by opcode02** [comment]
I ran MemTest86 overnight and found no memory errors. I did a Uninstall OS from ONIE and then loaded that image above first through dhcp/http, then did the Uninstall again and then installed that image directly from usb. Both times I get the same problem, missing i2c devices. 

Here is a complete bootlog, from reset to login:

[ag7648-bootlog.txt](https://github.com/bisdn/basebox/files/3772658/ag7648-bootlog.txt)

I'm about 90% convinced this is a problem in the coreboot and not higher the chain in linux, doesn't coreboot pass the device tree to the OS? Along these lines, I think the DIAG mode resets something and doesn't use the device tree from coreboot.

One other thing to note: Delta wanted me to try to reflash ONIE, using this guide: 

[ONIE-update](https://github.com/DeltaProducts/SolutionCenter/blob/master/ONIE%20recovery%20from%20bootable%20USB.pdf)

I tried that, the issue I have is there seems to be no way to get the bios (coreboot) to let me boot off usb, if I hit escape booting in the serial terminal I never seem to get any options it just eventually boots into grub, no matter how many times I hit escape. This also makes me think coreboot is messed up in some way.

**Comment by KanjiMonster** [comment]
Just a stab in the dark, could you please post the contents of
`/sys/devices/virtual/dmi/id/sys_vendor` and `/sys/devices/virtual/dmi/id/product_name` ?

**Comment by KanjiMonster** [comment]
Also a full bootlog with `debug` added to the kernel command line might be helpful.

**Comment by opcode02** [comment]
root@agema-ag7648:~# cat /sys/devices/virtual/dmi/id/sys_vendor
DNI
root@agema-ag7648:~# cat /sys/devices/virtual/dmi/id/sys_vendor
DNI

**Comment by opcode02** [comment]
`root@agema-ag7648:~# cat /sys/devices/virtual/dmi/id/sys_vendor`
DNI
`root@agema-ag7648:~# cat /sys/devices/virtual/dmi/id/product_name`
AG7648

**Comment by opcode02** [comment]
Here is full bootlog with debug passed into the kernel:

[bisdn-debug-boot.txt](https://github.com/bisdn/basebox/files/3820238/bisdn-debug-boot.txt)

**Comment by KanjiMonster** [comment]
Thank you very much! This confirms my suspicion, and is probably the root issue.

The code currently checks for the combinations of `Delta` and `AG7648` or `OEM` and `AG-7648PL`. But `DNI` / `AG7648` matches neither, so the code thinks it isn't running on an AG7648, and doesn't create any i2c devices. 

This should be an easy fix now that the we know what is "wrong".

**Comment by opcode02** [comment]
Wow, that's great news. Glad we finally tracked this down.

**Comment by KanjiMonster** [comment]
Please test if http://bisdn-switch-images.s3-eu-central-1.amazonaws.com/nightly_builds/agema-ag7648/master/onie-bisdn-testing-agema-ag7648-201911071652.bin works for you.

**Comment by opcode02** [comment]
That seems to work, I see lots of i2c devices now:
root@agema-ag7648:~# ls /dev/i2c*
/dev/i2c-0   /dev/i2c-12  /dev/i2c-16  /dev/i2c-2   /dev/i2c-23  /dev/i2c-27  /dev/i2c-30  /dev/i2c-34  /dev/i2c-38  /dev/i2c-41  /dev/i2c-45  /dev/i2c-49  /dev/i2c-52  /dev/i2c-56  /dev/i2c-6   /dev/i2c-63
/dev/i2c-1   /dev/i2c-13  /dev/i2c-17  /dev/i2c-20  /dev/i2c-24  /dev/i2c-28  /dev/i2c-31  /dev/i2c-35  /dev/i2c-39  /dev/i2c-42  /dev/i2c-46  /dev/i2c-5   /dev/i2c-53  /dev/i2c-57  /dev/i2c-60  /dev/i2c-7
/dev/i2c-10  /dev/i2c-14  /dev/i2c-18  /dev/i2c-21  /dev/i2c-25  /dev/i2c-29  /dev/i2c-32  /dev/i2c-36  /dev/i2c-4   /dev/i2c-43  /dev/i2c-47  /dev/i2c-50  /dev/i2c-54  /dev/i2c-58  /dev/i2c-61  /dev/i2c-8
/dev/i2c-11  /dev/i2c-15  /dev/i2c-19  /dev/i2c-22  /dev/i2c-26  /dev/i2c-3   /dev/i2c-33  /dev/i2c-37  /dev/i2c-40  /dev/i2c-44  /dev/i2c-48  /dev/i2c-51  /dev/i2c-55  /dev/i2c-59  /dev/i2c-62  /dev/i2c-9

Getting some weird errors from usb though that I didn't get before. 

[   20.086734] usb 1-1: device not accepting address 2, error -11
[   20.207735] usb 1-1: new high-speed USB device number 3 using ehci-pci
[   36.989387] usb usb1-port1: attempt power cycle
[   37.416742] usb 1-1: new high-speed USB device number 4 using ehci-pci
[   54.390736] usb 1-1: device not accepting address 4, error -110
[   54.510734] usb 1-1: new high-speed USB device number 5 using ehci-pci
[   71.286737] usb 1-1: device not accepting address 5, error -110
[   71.293394] usb usb1-port1: unable to enumerate USB device

Other than that nothing is complaining anymore.
