### ISSUE TITLE
Untagged packets on port without a PVID should be handled

### ISSUE THREAD

**Issue by hilmarm** [bisdn/basebox#347]
## Expected Behavior
If we recieve an untagged packet on a port where no pvid has been configured, we should expect the switch to drop the packet, and to get a log message. 

## Actual Behavior

file: src/netlink/nl_bridge.cc
786      // no vid, set vid to pvid                                                  
787      vid = br_vlan->pvid;      

As you see we simply set the vid pvid, which might be 0 (or something else?)

## Specifications
  - Version: 1.9.20
  - Platform: all
  - Subsystem: all

**Comment by KanjiMonster** [comment]
The code in question has been removed in https://github.com/bisdn/basebox/pull/366.
