### ISSUE TITLE
How set autoneg for interfaces

### ISSUE THREAD

**Issue by bidel65** [bisdn/basebox#427]
## Expected Behavior
be same below result for autoneg value for interfaces

#### client_drivshell command
Accton:~$ sudo client_drivshell ps             
Calling ofdpaBcmCommand rpc with command = "ps ".
Returned from ofdpaBcmCommand rpc with rc = 0.
File logging started to /tmp/.drivshell-output
                 ena/    speed/ link auto    STP                  lrn  inter   max  loop
           port  link    duplex scan neg?   state   pause  discrd ops   face frame  back
       ge0( 26)  up    1G  FD   SW  **Yes**  Forward          None  FAC  SGMII 16356     
       ge1( 25)  up    1G  FD   SW  **Yes**  Forward          None  FAC  SGMII 16356     
.
.
.

#### and ethtool command
Accton:~$ sudo ethtool port1
Settings for port1:
	Supported ports: [  ]
	Supported link modes:   Not reported
	Supported pause frame use: No
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: 1000Mb/s
	Duplex: Full
	Auto-negotiation: **off**
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	MDI-X: Unknown
	Link detected: yes

#### and we got error for set on with ethtool
Accton:~$ sudo ethtool -s port1 autoneg "on"
netlink error: Operation not supported

## Specifications
  - Version:4.8.3
  - Platform:accton as461054T
  - Subsystem:

**Comment by KanjiMonster** [comment]
Currently autonegotiation related values are not exposed via port interfaces, nor configurable.

Use `client_drivshell portstat` or `client_drivshell port` for the actual configuration and state.

You can configure autonegotiation via `client_drivshell port`:

`$ client_drivshell port 1 autoneg=<on|off>`

For a full reference of the supported arguments of `port`, see https://github.com/Broadcom-Network-Switching-Software/OpenBCM/blob/master/sdk-6.5.24/src/appl/diag/esw_diag.c#L846. It also allows you configuring which speeds are advertised, in case you want to limit them.

**Comment by KanjiMonster** [comment]
Neither of the chosen abstractions for switch ports (tap devices and knet devices) support configuring or exposing auto-negotiation capabilities.

**Comment by bidel65** [comment]
Ok, so what is the usage for changing autoneg with `client_drivshell port`

**Comment by jklare** [comment]
The documentation on how to change autoneg with client_drivshell can be found in our docs here: https://docs.bisdn.de/platform_configuration/auto_negotiation.html @bidel65
